### ISSUE TITLE
Wak fmt

### ISSUE THREAD

**Issue by danielsz** [ktakashi/sagittarius-scheme#2]
Hi, 

I was repeating the steps from a Akku.scm [demo](https://weinholt.se/articles/introduction-to-akku-scm/) and tried to run it with sagittarius, there seems to be an error with one of the imports of the [wak fmt](https://gitlab.com/wak/wak-fmt) dependency. The demo does work out of the box with guile, plt-r6rs and chez-scheme, so I'm not sure where to ask about the error (Akku.scm or here). Do you know what the problem is?

``` sh
Unhandled exception
  Condition components:
  1. &compile
    program: (import (rnrs (6)) (sbank-hello))
    source: "bin/sbank-hello.sps":7
  2. &compile
    program: (library (sbank-hello) (export hello) (import (rnrs) (wak fm
    source: "/home/arch/daniel/scheme/projects/akku/sbank-hello/sbank-hello.sls":6
  3. &compile
    program: (library (wak fmt) (export new-fmt-state fmt fmt-start fmt-i
    source: "/home/arch/daniel/scheme/projects/akku/sbank-hello/.akku/lib/wak/fmt.sls":10
  4. &compile
    program: (library (srfi :6 basic-string-ports) (export (rename (open-
    source: "/home/arch/daniel/scheme/projects/akku/sbank-hello/.akku/lib/srfi/:6/basic-string-ports.sls":5
  5. &error
  6. &message import no such library ((srfi :6 basic-string-ports compat))
  7. &stack-trace
```

**Comment by danielsz** [comment]
The author of Akku.scm explained that the error happens because `chez-srfi` has special support for Racket and guile.

**Comment by ktakashi** [comment]
Sagittarius supports a large number of SRFIs and SRFI-6 is one of them. I think in this case, it'd be better not to install chez-srfi or at least remove it from the load path.

An alternative way would be using `-A` command line option instead of `-L`. Though not sure if this is applicable for akku.

**Comment by danielsz** [comment]
This makes sense, thank you. Akku.scm will probably address this in the context of issue [19](https://gitlab.com/akkuscm/akku/issues/19).
